name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: установка ключа
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: установка зависимостей
        run: |
          composer update --ignore-platform-req=php+ -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci --force
          npm run build

      - name: замена переменных окружения
        run: |
          cp .env.example .env
          php artisan key:generate
          sed -i "s/APP_DEBUG=true/APP_DEBUG=false/" .env
          sed -i "s/DB_HOST=mysql/DB_HOST=${{ secrets.db_host }}/" .env
          sed -i "s/DB_DATABASE=site_check/DB_DATABASE=${{ secrets.db_name }}/" .env
          sed -i "s/DB_USERNAME=sail/DB_USERNAME=${{ secrets.db_login }}/" .env
          sed -i "s/DB_PASSWORD=password/DB_PASSWORD=${{ secrets.db_password }}/" .env
          sed -i "s/MAIL_HOST=mailhog/MAIL_HOST=${{ secrets.mail_host }}/" .env
          sed -i "s/MAIL_USERNAME=null/MAIL_USERNAME=${{ secrets.mail_username }}/" .env
          sed -i "s/MAIL_PASSWORD=null/MAIL_PASSWORD=${{ secrets.mail_password }}/" .env
          sed -i "s/TG_TOKEN=/TG_TOKEN=${{ secrets.tg_token }}/" .env

      - name: синхронизация файлов с хостингом
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . "${{ secrets.login }}@${{ secrets.host }}:${{ secrets.path_site }}" --exclude node_modules/

      - name: проведение миграций
        run: ssh -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no "${{ secrets.login }}@${{ secrets.host }}" "cd ${{ secrets.path_site }}; /opt/php/8.1/bin/php artisan migrate:reset; /opt/php/8.1/bin/php artisan migrate --seed"
